name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: (cd jfgrea27.github.io && hugo --minify)

      - name: Add CNAME
        run: |
          echo "www.jfgrea27.xyz../.github/workflows/hugo.yaml" > jfgrea27.github.io/public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./jfgrea27.github.io/public
          publish_branch: gh-pages